name: Synk Testing

on:
  push:


jobs:
  synk_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Snyk to check for vulnerabilities
      run: |
        npm install -g snyk 
        snyk monitor
