name: Synk Testing

on:
  push:
    branches:
      - main

jobs:
  synk_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        args: test
      env:
        SNYK_TOKEN: 8f7286c8-8b61-4cfa-a48f-f56d82fa95c1
